[project]
name = "42-ft-linear-regression"
version = "0.1.0"
description = "A linear regression model from scratch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
]
